// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface _CalcOperations
{
    float add1(float a, float b, Ice.Current __current);

    void add2_async(AMD_Calc_add2 __cb, float a, float b, Ice.Current __current)
        throws RequestCanceledException;

    float subtract(float a, float b, Ice.Current __current);
}
