// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface UserManagementPrx extends Ice.ObjectPrx
{
    public UserPrx createUser();

    public UserPrx createUser(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createUser();

    public Ice.AsyncResult begin_createUser(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createUser(Ice.Callback __cb);

    public Ice.AsyncResult begin_createUser(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_createUser(Callback_UserManagement_createUser __cb);

    public Ice.AsyncResult begin_createUser(java.util.Map<String, String> __ctx, Callback_UserManagement_createUser __cb);

    public Ice.AsyncResult begin_createUser(IceInternal.Functional_GenericCallback1<UserPrx> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createUser(IceInternal.Functional_GenericCallback1<UserPrx> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_createUser(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<UserPrx> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createUser(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<UserPrx> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public UserPrx end_createUser(Ice.AsyncResult __result);

    public UserPrx[] findUsers(String template);

    public UserPrx[] findUsers(String template, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findUsers(String template);

    public Ice.AsyncResult begin_findUsers(String template, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_findUsers(String template, Ice.Callback __cb);

    public Ice.AsyncResult begin_findUsers(String template, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_findUsers(String template, Callback_UserManagement_findUsers __cb);

    public Ice.AsyncResult begin_findUsers(String template, java.util.Map<String, String> __ctx, Callback_UserManagement_findUsers __cb);

    public Ice.AsyncResult begin_findUsers(String template, 
                                           IceInternal.Functional_GenericCallback1<UserPrx[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findUsers(String template, 
                                           IceInternal.Functional_GenericCallback1<UserPrx[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_findUsers(String template, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<UserPrx[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_findUsers(String template, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<UserPrx[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public UserPrx[] end_findUsers(Ice.AsyncResult __result);
}
