// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface UserManagement extends Ice.Object,
                                        _UserManagementOperations, _UserManagementOperationsNC
{
    public static final String ice_staticId = "::demo::UserManagement";

    public static final long serialVersionUID = -1211230084L;
}
