// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface UserPrx extends Ice.ObjectPrx
{
    public long getId();

    public long getId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getId();

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getId(Ice.Callback __cb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getId(Callback_User_getId __cb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, Callback_User_getId __cb);

    public Ice.AsyncResult begin_getId(IceInternal.Functional_LongCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getId(IceInternal.Functional_LongCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_LongCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getId(java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_LongCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public long end_getId(Ice.AsyncResult __result);

    public Name getName();

    public Name getName(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getName();

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getName(Ice.Callback __cb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getName(Callback_User_getName __cb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, Callback_User_getName __cb);

    public Ice.AsyncResult begin_getName(IceInternal.Functional_GenericCallback1<Name> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getName(IceInternal.Functional_GenericCallback1<Name> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<Name> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getName(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<Name> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Name end_getName(Ice.AsyncResult __result);

    public void changeName(Name name1);

    public void changeName(Name name1, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_changeName(Name name1);

    public Ice.AsyncResult begin_changeName(Name name1, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_changeName(Name name1, Ice.Callback __cb);

    public Ice.AsyncResult begin_changeName(Name name1, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_changeName(Name name1, Callback_User_changeName __cb);

    public Ice.AsyncResult begin_changeName(Name name1, java.util.Map<String, String> __ctx, Callback_User_changeName __cb);

    public Ice.AsyncResult begin_changeName(Name name1, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_changeName(Name name1, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_changeName(Name name1, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_changeName(Name name1, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_changeName(Ice.AsyncResult __result);
}
