spring:
  application:
      name: IOSR-node

logging:
  level:
    ROOT: INFO

amqp:
  queue: queue-${raft.name}
  exchange: raft-exchange
  routingKey: ${raft.name}

raft:
  name: node
  nodes:




