CC = gcc -Wall
P1 = client

# C

all: clean compile

clean:
	rm -f $(P1)

compile:
	$(CC) $(P1).c -o $(P1)
	

PROJ = ex1

#JAVA

java_clean:
	ant clean

java_compile:
	ant

java_run:
	java -jar $(PROJ).jar